#!/usr/bin/make -f
# Makefile for se3_ocs

all:

install:
    # Add here commands to install the package into debian/Se3.
    # Install des fichiers de configuration et de cron.
    cp -R install-scriptŝ/* $(DESTDIR)/var/cache/se3_install/radius/
	
clean:
